config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :islands
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/island.rb
class Island < ApplicationRecord
  belongs_to :user
  has_many_attached :photos

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  CATEGORY = %w(Tidal Barrier Oceanic Coral Continental Artificial)

  # validates :name, presence: true
  # validates :location, presence: true
  # validates :description, presence: true
  # validates :category, presence: true
  # validates :price_per_night, presence: true, numericality: true
  # validates :deposit, presence: true, numericality: true

  def category
    CATEGORY
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook]

  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice("provider", "uid")
    user_params.merge! auth.info.slice("email", "first_name", "last_name")
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/islands_controller.rb
class IslandsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :find_island, only: %i[edit update show destroy]

  def index
    @islands = Island.all
    @markers = @islands.geocoded.map do |island|
      {
        lat: island.latitude,
        lng: island.longitude,
        info_window: render_to_string(partial: "info_window", locals: {island: island})
      }
    end
  end

  def new
    @island = Island.new
  end

  def create
    @island = Island.new(island_params)
    @island.user = current_user
    if @island.save
      redirect_to island_path(@island)
    else
      render :new
    end
  end

  def show
  end

  def edit
    @user = current_user
  end

  def update
    if @island.update(island_params)
      redirect_to island_path
    else
      render :new
    end
  end

  def destroy
    # if @surfboard.bookings.count.zero?
    #   @surfboard.destroy
    #   @message = 'Your surfboard has been deleted.'
    # else
    #   @message = 'You can not delete this surfboard because it has been booked.'
    # end
    @island.destroy
    redirect_to islands_path
  end

  private

  def find_island
    @island = Island.find(params[:id])
  end

  def island_params
    params.require(:island).permit(:name, :location, :price_per_night, :description, :longitude, :latitude, :photos, :deposit, :category)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/islands/_edit.html.erb
<div class="modal fade" id="islandEditModal" tabindex="-1" aria-labelledby="islandEditModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="islandEditModalLabel">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= simple_form_for @island do |f| %>
          <%= f.input :name,
                      input_html: { class: "form__input"},
                      label_html: { class: "form__label"} %>
          <%= f.input :price_per_night, label: "Price per Day",
                      input_html: { class: "form__input"},
                      label_html: { class: "form__label"} %>
          <%= f.input :description, label: "Please enter a detailed description about your item, including its condition",
                      input_html: { class: "form__input"},
                      label_html: { class: "form__label"} %>
          <%= f.input :location, label: "Pick up location",
                      input_html: { class: "form__input"},
                      label_html: { class: "form__label"} %>
          <%= f.input :photo, as: :file,
                      label_html: { class: "form__label"} %>
          <%= f.button :submit , class: "btn btn-primary w-100" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/islands/_info_window.html.erb
<h2><%= island.name %></h2>
<p><%= island.location %></p>

app/views/islands/create.html.erb
<h1>Islands#create</h1>
<p>Find me in app/views/islands/create.html.erb</p>

app/views/islands/index.html.erb
<h1>Browse Islands</h1>

<div style="width: 100%; height: 600px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

<% @islands.each do |island| %>
  <%= link_to island_path(island) do %>
    <h3><%= island.name %></h3>
  <% end %>
  <p><%= island.description %></p>
  <% island.photos.each do |photo| %>
    <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
  <% end %>
<% end %>

app/views/islands/new.html.erb
<h1>Create a new listing</h1>

<%= simple_form_for @island do |f| %>
  <%= f.input :name,
              input_html: { class: "form__input"},
              label_html: { class: "form__label"} %>
  <%= f.input :category, as: :radio_buttons, collection: @island.category,
              input_html: { class: "form__input"},
              label_html: { class: "form__label"} %>
  <%= f.input :price_per_night, label: "Price per day",
              input_html: { class: "form__input"},
              label_html: { class: "form__label"} %>
  <%= f.input :deposit,
              input_html: { class: "form__input"},
              label_html: { class: "form__label"} %>
  <%= f.input :description, label: "Please enter a detailed description about your island",
              input_html: { class: "form__input"},
              label_html: { class: "form__label"} %>
    <%= f.input :location, label: "What is the islands' location",
                input_html: { class: "form__input"},
                label_html: { class: "form__label"}%>
  <%= f.input :photos, as: :file,
              input_html: { multiple: true },
              label_html: { class: "form__label"} %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/islands/show.html.erb
<%= link_to "< Back", :back, class: "link" %>

<h1><%= @island.name %></h1>
<p><%= @island.description %></p>
<p>$<%= @island.price_per_night %> per night</p>
<p><%= @island.location %></p>

<!-- Images -->
<% @island.photos.each do |photo| %>
  <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
<% end %>

<!-- Edit & delete -->
<div>
  <% if current_user == @island.user %>
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#islandEditModal">
      Edit listing
    </button>
    <%= link_to "Delete", island_path(@island), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary" %>
  <% end %>
</div>

<%= render 'edit' %>

app/views/islands/update.html.erb
<h1>Islands#update</h1>
<p>Find me in app/views/islands/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rent An Island</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <link href="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.js"></script>
  </head>

  <body>
    <%= render 'shared/navbar' %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>

    <%= render 'shared/flashes' %>
  </body>
</html>

app/views/pages/home.html.erb
<%= link_to  "Create a new listing", new_island_path %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <% avatar_url = current_user.facebook_picture_url || "https://kitt.lewagon.com/placeholder/users/ssaunier" %>
            <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>